export class VoteDetail {
    id?: string;
    nameSinhala: string;
    nameEnglish: string;
    nameTamil: string;
    code: string;
    status: number;
    sabhaID: number;
    voteOrder : number;
    programmeID : number;
    programmeNameSinhala : string;
    programmeNameEnglish : string;
    programmeNameTamil : string;
    programmeCode : string;
    projectID : number;
    projectNameSinhala : string;
    projectNameEnglish : string;
    projectNameTamil : string;
    projectCode : string;
    subprojectID : number;
    subprojectNameSinhala : string;
    subprojectNameEnglish : string;
    subprojectNameTamil : string;
    subprojectCode : string;
    incomeTitleID : number;
    incomeTitleNameSinhala : string;
    incomeTitleNameEnglish : string;
    incomeTitleNameTamil : string;
    incomeTitleCode : string;
    incomeSubtitleID : number;
    incomeSubtitleNameSinhala : string;
    incomeSubtitleNameEnglish : string;
    incomeSubtitleNameTamil : string;
    incomeSubtitleCode : string;
    incomeOrExpense : number;
    voteOrBal : number;
    sabhaCode : string;
    balancesheetTitleID : number;
    balancesheetSubtitleID : number;
}
